version: "3"

services:
  api:
    image: nightstalker5699/backend
    mem_limit: 128m
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - PGUSER
      - PGHOST
      - PGDATABASE
      - PGPASSWORD
      - PGPORT
  worker:
    image: nightstalker5699/worker
    mem_limit: 128m
    environment:
      - REDIS_HOST
      - REDIS_PORT
  client:
    image: nightstalker5699/client
    mem_limit: 128m

  nginx:
    image: nightstalker5699/nginx
    mem_limit: 128m
    ports:
      - 80:80
