name: deploy the project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout node
        uses: actions/checkout@v2
      - name: log to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: tests
        run: docker build -t frontend -f ./client/dockerfile.dev ./client
      - name: run the tests
        run: docker run -e CI=true frontend npm test
      - run: docker build -t nightstalker5699/backend ./server
      - run: docker build -t nightstalker5699/worker ./worker
      - run: docker build -t nightstalker5699/nginx ./nginx
      - run: docker build -t nightstalker5699/client ./client

      - run: docker push nightstalker5699/backend
      - run: docker push nightstalker5699/worker
      - run: docker push nightstalker5699/nginx
      - run: docker push nightstalker5699/client
